### ISSUE TITLE
Fly Type B/C ff + Command Errors

### ISSUE THREAD

**Issue by Vantrex** [funkemunky/Iris-Issues#44]
**Describe the bug**
Fly B & Fly C falseflag.

**Version Information**
- latest (cant see the ver. ingame via command)
- 1.0.8.1
- paperspigot 1.8.8

**Server Logs**
command error: (/atlas: https://pastebin.com/3FniSrEE /iris 2: https://pastebin.com/MChA5cC0 )

**How to re-create**
Describe in detail how we can re-create this bug.
Jump from the edge of a block

**Additional context**
Idk if it is fixed now, but you cant use the "IrisCheatEvent"

**Comment by funkemunky** [comment]
Did you by chance reload your server? This definitely seems to be limited by just you. The reason I think this is because you do not provide much detail into how you recreate it, lol. You have to give **detailed steps**!

I'm closing this issue since it needs to be heavily revised before I can even use this.
