### ISSUE TITLE
Players cant jump etc.

### ISSUE THREAD

**Issue by jonas3377** [funkemunky/Iris-Issues#73]
**Describe the bug**
Players have no permissions
They are not allowed to jump or run
they cant use enchanted pickaxes, as they mine to fast. then it must be a cheat..
they cant use elytra.
etc..

**Version Information**
- Iris Anticheat Version 1.8.0
- Atlas Version 1.1.4
- Bukkit/Spigot Version 1.13.2-R0.1-Snapshot

**Are you using the ViaVersion plugin?**
nope

**Server Logs**
Provide the server log of the time the bug occurred.
https://github.com/jonas3377/Log1/blob/master/log1

**How to re-create**
Describe in detail how we can re-create this bug.
Steps:
1) installed the plugin
2) logged in as a normal rank person
3) jumped normally
4) jump from stairs is not possible

**Screenshots/Video**
https://imgur.com/a/CV2v1Gh

**Additional context**

**Comment by FozzieHi** [comment]
Are you running PaperSpigot?

**Comment by jonas3377** [comment]
> Are you running PaperSpigot?

nope just spigot 1.13.2

**Comment by jonas3377** [comment]
still fucked up..

**Comment by FozzieHi** [comment]
@funkemunky this is still broken with regular Spigot.

**Comment by funkemunky** [comment]
I actually do not remember adding compatibility for 1.13.2 in Atlas yet. Are there errors?

**Comment by FozzieHi** [comment]
@funkemunky https://github.com/jonas3377/Log1/blob/master/log1

**Comment by funkemunky** [comment]
This is going to be an incredibly difficult fix because 1.13 is R13_1 in the bukkit package tree, and 1.13.1 and 1.13.2 is R13_2. Basically, it means that there is no discernible way to tell the difference between each version. 

So, it seems in some update they decided to remove a useful method that allowed me to convert the collision boxes from VoxelShapes to the legacy AxisAlignedBB class. The new VoxelShape system is actually quite a pain in the ass to use, so it will be awhile before I support it.

**Comment by FozzieHi** [comment]
@jonas3377 for now I'd recommend using 1.13.1

**Comment by jonas3377** [comment]
thank u :D
